language: python

virtualenv:
  system_site_packages: true

sudo: required

services:
  - docker

before_install:
  - git clone --recurse-submodules git://github.com/openmicroscopy/test-omero .omero

script:
  - .omero/cli-docker
